// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutTracker.Data.Models;

namespace WorkoutTracker.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200628210452_AddedMovementSet")]
    partial class AddedMovementSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WorkoutTracker.Data.Models.Entities.MovementsMuscleGroups", b =>
                {
                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<int>("MusclGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.HasKey("MovementId", "MusclGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("MovementsMuscleGroups");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MovementId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PatternId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatternId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.MovementPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MovementPatterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Hinge"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Lunge"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Push"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Pull"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Carry"
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Entities.MovementsMuscleGroups", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.Movement", "Movement")
                        .WithMany("MovementsMuscleGroups")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Data.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MovementsMuscleGroups")
                        .HasForeignKey("MuscleGroupId");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Equipment", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.Movement", null)
                        .WithMany("EquipmentNeeded")
                        .HasForeignKey("MovementId");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Movement", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.MovementPattern", "Pattern")
                        .WithMany()
                        .HasForeignKey("PatternId");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Muscle", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.MuscleGroup", null)
                        .WithMany("MusclesWorked")
                        .HasForeignKey("MuscleGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
