// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkoutTracker.Data.Models;

namespace WorkoutTracker.Data.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("WorkoutTracker.Data.Models.Entities.MovementsMuscleGroups", b =>
                {
                    b.Property<int>("MovementId")
                        .HasColumnType("integer");

                    b.Property<int>("MusclGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MovementId", "MusclGroupId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("MovementsMuscleGroups");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MovementId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1489),
                            IsActive = true,
                            Name = "Barbell",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1500)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1521),
                            IsActive = true,
                            Name = "Dumbell",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1523)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1525),
                            IsActive = true,
                            Name = "Jump Rope",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1526)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1527),
                            IsActive = true,
                            Name = "Bench",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(1528)
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PatternId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatternId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.MovementPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MovementPatterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(5363),
                            IsActive = true,
                            Name = "Hinge",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(5502)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6844),
                            IsActive = true,
                            Name = "Squat",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6849)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6870),
                            IsActive = true,
                            Name = "Lunge",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6871)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6873),
                            IsActive = true,
                            Name = "Push",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6874)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6875),
                            IsActive = true,
                            Name = "Pull",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6876)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6878),
                            IsActive = true,
                            Name = "Carry",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 828, DateTimeKind.Utc).AddTicks(6879)
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.WorkoutType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2446),
                            IsActive = true,
                            Name = "Full",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2451)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2471),
                            IsActive = true,
                            Name = "Strength",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2472)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2475),
                            IsActive = true,
                            Name = "Metabolic Conditioning",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2476)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2477),
                            IsActive = true,
                            Name = "Active Recovery",
                            UpdatedAt = new DateTime(2020, 7, 17, 20, 33, 3, 830, DateTimeKind.Utc).AddTicks(2478)
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Entities.MovementsMuscleGroups", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.Movement", "Movement")
                        .WithMany("MovementsMuscleGroups")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Data.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("MovementsMuscleGroups")
                        .HasForeignKey("MuscleGroupId");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Equipment", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.Movement", null)
                        .WithMany("EquipmentNeeded")
                        .HasForeignKey("MovementId");
                });

            modelBuilder.Entity("WorkoutTracker.Data.Models.Movement", b =>
                {
                    b.HasOne("WorkoutTracker.Data.Models.MovementPattern", "Pattern")
                        .WithMany()
                        .HasForeignKey("PatternId");
                });
#pragma warning restore 612, 618
        }
    }
}
